# Generated by Django 4.2.4 on 2023-09-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_direccion_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
